In [2]:
import json

employees = [
    {
        "name": "Imran Abdul",
        "DOB": "04-07-1994",
        "height": "5'7\"",
        "city": "Hyderabad",
        "state": "Telangana State",
    },
    {
        "name": "Nikola Tesla",
        "DOB": "10-07-1972",
        "height": "5'10\"",
        "city": "Banglore",
        "state": "Karnataka",
    },
    {
        "name": "Albert Einstein",
        "DOB": "14-03-1978",
        "height": "5'9\"",
        "city": "Chennai",
        "state": "Tamil Nadu",
    },
    {
        "name": "Carl Sagan",
        "DOB": "23-12-1983",
        "height": "5'8\"",
        "city": "Mumbai",
        "state": "Maharashtra",
    },
    {
        "name": "Mary Curie",
        "DOB": "19-04-1979",
        "height": "5'5\"",
        "city": "Gandhinagar",
        "state": "Gujarat",
    },
    {
        "name": "Neil deGrasse Tyson",
        "DOB": "12-08-1989",
        "height": "5'10\"",
        "city": "Itanagar",
        "state": "Arunachal Pradesh",
    },
]


with open("employee.json", "w") as file:
    json.dump(employees, file)

class Employee:
    def __init__(self, name, DOB, height, city, state):
        self.name = name
        self.DOB = DOB
        self.height = height
        self.city = city
        self.state = state

def read_employee_info(filename):

    employee_list = []

    with open(filename, "r") as f:
        data = json.load(f)

    for employee in data:
        employee_list.append(
            Employee(
                employee["name"],
                employee["DOB"],
                employee["height"],
                employee["city"],
                employee["state"],
            )
        )

    return employee_list


def main():

    file_path = r"employee.json"
    emp_list = read_employee_info(file_path)

    for employee in emp_list:
        print(f"Name: {employee.name}")
        print(f"DOB: {employee.DOB}")
        print(f"Height: {employee.height}")
        print(f"City: {employee.city}")
        print(f"State: {employee.state}")
        print("----------------")


if __name__ == "__main__":
    main()

Name: Imran Abdul
DOB: 04-07-1994
Height: 5'7"
City: Hyderabad
State: Telangana State
----------------
Name: Nikola Tesla
DOB: 10-07-1972
Height: 5'10"
City: Banglore
State: Karnataka
----------------
Name: Albert Einstein
DOB: 14-03-1978
Height: 5'9"
City: Chennai
State: Tamil Nadu
----------------
Name: Carl Sagan
DOB: 23-12-1983
Height: 5'8"
City: Mumbai
State: Maharashtra
----------------
Name: Mary Curie
DOB: 19-04-1979
Height: 5'5"
City: Gandhinagar
State: Gujarat
----------------
Name: Neil deGrasse Tyson
DOB: 12-08-1989
Height: 5'10"
City: Itanagar
State: Arunachal Pradesh
----------------